services:
  postgres:
    image: postgres:16-alpine
    container_name: drklawz-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drklawz
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: drklawz-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@drklawz.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local
